### ISSUE TITLE
Not working with VCC audiolink in unity 2022.3.6f1

### ISSUE THREAD

**Issue by RaspberryKitty1** [Blabzillaweasel/AudioLink-USharpVideo-Adapter#5]
`Assets\Audiolink (USharpVideo Adapter)\Scripts\Audiolink_USVideo_Adapter.cs(17,22): error CS0234: The type or namespace name 'AudioLink' does not exist in the namespace 'VRCAudioLink' (are you missing an assembly reference?)`

im using the audiolink package from the vrchat creator companion tool. and latest supported version of unity for vrchat SDK. 2022.3.6f1

**Comment by Blabzillaweasel** [comment]
I've just uploaded V1.0.0 which fixes this.
